# Generated by Django 6.0.2 on 2026-02-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICTFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_experience', models.TextField(blank=True)),
                ('facilities_satisfaction', models.TextField(blank=True)),
                ('instructor_effectiveness', models.TextField(blank=True)),
                ('useful_courses', models.TextField(blank=True)),
                ('improvement_areas', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
