# Generated by Django 6.0.2 on 2026-02-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_rename_facilities_satisfaction_ictfeedback_academic_guidance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ictfeedback',
            name='academic_guidance',
        ),
        migrations.RemoveField(
            model_name='ictfeedback',
            name='additional_courses',
        ),
        migrations.RemoveField(
            model_name='ictfeedback',
            name='communication_effectiveness',
        ),
        migrations.RemoveField(
            model_name='ictfeedback',
            name='computer_functionality',
        ),
        migrations.RemoveField(
            model_name='ictfeedback',
            name='industry_readiness',
        ),
        migrations.RemoveField(
            model_name='ictfeedback',
            name='lab_sessions_helpfulness',
        ),
        migrations.RemoveField(
            model_name='ictfeedback',
            name='module_improvement',
        ),
        migrations.RemoveField(
            model_name='ictfeedback',
            name='module_structure',
        ),
        migrations.RemoveField(
            model_name='ictfeedback',
            name='practical_sessions',
        ),
        migrations.RemoveField(
            model_name='ictfeedback',
            name='project_application',
        ),
        migrations.RemoveField(
            model_name='ictfeedback',
            name='software_status',
        ),
        migrations.RemoveField(
            model_name='ictfeedback',
            name='student_participation',
        ),
        migrations.RemoveField(
            model_name='ictfeedback',
            name='technical_support',
        ),
        migrations.RemoveField(
            model_name='ictfeedback',
            name='training_quality_suggestions',
        ),
        migrations.AlterField(
            model_name='ictfeedback',
            name='computer_lab_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='ictfeedback',
            name='industry_relevance',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='ictfeedback',
            name='instructor_effectiveness',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='ictfeedback',
            name='internet_reliability',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='ictfeedback',
            name='lesson_clarity',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='ictfeedback',
            name='overall_experience',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='ictfeedback',
            name='practical_examples',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='ictfeedback',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ictfeedback',
            name='training_satisfaction',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
    ]
